apiVersion: dp.wso2.com/v1alpha1
kind: Authentication
metadata:
  name: sand-http-bin-authentication
spec:
  override:
    type: ext
    ext:
      disabled: true
      serviceRef:
        group: wso2/v1alpha2
        kind: Backend
        name: ext_authz-server
        port: 1234
      authTypes:
        - type: jwt
        - type: apiKey
  default:
    type: ext
    ext:
      serviceRef: 
        group: wso2/v1alpha2
        kind: Backend
        name: ext_authz-server
        port: 1234
      authTypes:
        - type: jwt
        - type: apiKey
  targetRef:
    kind: API
    name: http-bin-api #provide API ref name
    group: gateway.networking.k8s.io