/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/policies/search": {
    /**
     * Retrieve/Search Policies
     *  
     * @description This operation provides you a list of available Policies qualifying the given keyword match.
     */
    get: operations["policySearch"];
  };
  "/application-rate-plans": {
    /**
     * Get all Application Rate Plans 
     * @description Retrieves all existing application rate plans.
     */
    get: operations["getApplicationRatePlans"];
    /**
     * Add an Application Rate Plan 
     * @description This operation can be used to add a new application level rate plan.
     */
    post: operations["addApplicationRatePlan"];
  };
  "/application-rate-plans/{planId}": {
    /**
     * Get an Application Rate Plan 
     * @description Retrieves an application rate plan.
     */
    get: operations["getApplicationRatePlanById"];
    /**
     * Update an Application Rate Plan 
     * @description Updates an existing application level rate plan. Upon a successful update, you will receive the updated application plan as the response.
     */
    put: operations["updateApplicationRatePlan"];
    /**
     * Delete an Application Rate Plan 
     * @description Deletes an application level rate plan.
     */
    delete: operations["removeApplicationRatePlan"];
  };
  "/business-plans": {
    /**
     * Get all Business Plans 
     * @description This operation can be used to retrieve all Business Plans.
     */
    get: operations["getAllBusinessPlans"];
    /**
     * Add a Business Plan 
     * @description This operation can be used to add a  Business Plan specifying the details of the plan in the payload.
     */
    post: operations["addBusinessPlan"];
  };
  "/business-plans/{planId}": {
    /**
     * Get a Business Plan 
     * @description This operation can be used to retrieves Business Plan by specifying the Id of the plan as a path parameter
     */
    get: operations["getBusinessPlanById"];
    /**
     * Update a Business Plan 
     * @description Updates an existing Business Plan.
     */
    put: operations["updateBusinessPlan"];
    /**
     * Delete a Business Plan 
     * @description This operation can be used to delete a business plan by specifying the Id of the plan as a path parameter.
     */
    delete: operations["removeBusinessPlan"];
  };
  "/throttling/policies/export": {
    /**
     * Export a Throttling Policy 
     * @description This operation can be used to export the details of a particular Throttling Policy.
     */
    get: operations["exportThrottlingPolicy"];
  };
  "/throttling/policies/import": {
    /**
     * Import a Throttling Policy 
     * @description This operation can be used to import a Throttling Policy.
     */
    post: operations["importThrottlingPolicy"];
  };
  "/deny-policies": {
    /**
     * Get all Deny Policies 
     * @description Retrieves all existing deny policies.
     */
    get: operations["getAllDenyPolicies"];
    /**
     * Add a deny policy 
     * @description Adds a new deny policy
     */
    post: operations["addDenyPolicy"];
  };
  "/deny-policies/{policyId}": {
    /**
     * Get a Deny Policy 
     * @description Retrieves a Deny policy providing the policy Id
     */
    get: operations["getDenyPolicyById"];
    /**
     * Delete a Deny Policy 
     * @description Deletes an existing deny policy
     */
    delete: operations["removeDenyPolicy"];
    /**
     * Update a Deny Policy 
     * @description Update a deny policy by Id
     */
    patch: operations["updateDenyPolicy"];
  };
  "/applications": {
    /**
     * Retrieve/Search Applications
     *  
     * @description This operation can be used to retrieve list of applications owned by the given user, If no user
     * is provided, the applications owned by the user associated with the provided access token will be returned.
     */
    get: operations["getApplicationsByUser"];
  };
  "/applications/{applicationId}": {
    /**
     * Get the details of an Application
     *  
     * @description This operation can be used to get the details of an application by specifying its id.
     */
    get: operations["getApplicationById"];
    /**
     * Delete an Application
     *  
     * @description This operation can be used to delete an application by specifying its id.
     */
    delete: operations["removeApplication"];
  };
  "/applications/{applicationId}/change-owner": {
    /**
     * Change Application Owner 
     * @description This operation is used to change the owner of an Application.
     * In order to change the owner of an application, we need to pass the new application owner as a query parameter
     */
    post: operations["changeApplicationOwner"];
  };
  "/environments": {
    /**
     * Get all registered Environments 
     * @description Get all Registered Environments
     */
    get: operations["getEnvironments"];
    /**
     * Add an Environment 
     * @description Add a new gateway environment
     */
    post: operations["addEnvironment"];
  };
  "/environments/{environmentId}": {
    /**
     * Update an Environment 
     * @description Update a gateway Environment by environment Id
     */
    put: operations["updateEnvironment"];
    /**
     * Delete an Environment 
     * @description Delete a Environment by Environment Id
     */
    delete: operations["removeEnvironment"];
  };
  "/tenant-info/{username}": {
    /**
     * Get Tenant Id of User
     *  
     * @description This operation is to get tenant id of the provided user
     */
    get: operations["getTenantInfoByUsername"];
  };
  "/custom-urls/{tenantDomain}": {
    /**
     * Get Custom URL Info of a Tenant Domain
     *  
     * @description This operation is to get custom-url information of the provided tenant-domain
     */
    get: operations["getCustomUrlInfoByTenantDomain"];
  };
  "/api-categories": {
    /**
     * Get all API Categories 
     * @description Get all API categories
     */
    get: operations["getAllCategories"];
    /**
     * Add API Category 
     * @description Add a new API category
     */
    post: operations["addCategory"];
  };
  "/api-categories/{apiCategoryId}": {
    /**
     * Update an API Category 
     * @description Update an API Category by category Id
     */
    put: operations["updateCategory"];
    /**
     * Delete an API Category 
     * @description Delete an API Category by API Category Id
     */
    delete: operations["removeCategory"];
  };
  "/settings": {
    /**
     * Retrieve Admin Settings 
     * @description Retrieve admin settings
     */
    get: operations["getAdminSettings"];
  };
  "/key-managers": {
    /**
     * Get all Key managers 
     * @description Get all Key managers
     */
    get: operations["getAllKeyManagers"];
    /**
     * Add a new API Key Manager 
     * @description Add a new API Key Manager
     */
    post: operations["addNewKeyManager"];
  };
  "/key-managers/{keyManagerId}": {
    /**
     * Get a Key Manager Configuration 
     * @description Retrieve a single Key Manager Configuration. We should provide the Id of the KeyManager as a path parameter.
     */
    get: operations["getKeyManagerConfiguration"];
    /**
     * Update a Key Manager 
     * @description Update a Key Manager by keyManager ID
     */
    put: operations["updateKeyManager"];
    /**
     * Delete a Key Manager 
     * @description Delete a Key Manager by keyManager id
     */
    delete: operations["removeKeyManager"];
  };
  "/key-managers/discover": {
    /**
     * Retrieve Well-known information from Key Manager Well-known Endpoint 
     * @description Retrieve well-known information from key manager's well-known endpoint
     */
    post: operations["getWellKnownInfoKeyManager"];
  };
  "/organizations": {
    /**
     * Get all Organization 
     * @description Get all Organization
     */
    get: operations["getAllOrganization"];
    /**
     * Add Organization 
     * @description Add a new Organization
     */
    post: operations["addOrganization"];
  };
  "/organizations/{organizationId}": {
    /**
     * Get the details of an Organization
     *  
     * @description This operation can be used to get the details of an Organization by specifying its id.
     */
    get: operations["getOrganizationById"];
    /**
     * Update an Organization 
     * @description Update an Organization by organization Id
     */
    put: operations["updateOrganization"];
    /**
     * Delete an Organization 
     * @description Delete an Organization by API Organization Id
     */
    delete: operations["removeOrganization"];
  };
  "/organization-info": {
    /**
     * Authenticate Organization info
     *  
     * @description This operation can be used to authenticate Organization by specifying its claimValue.
     */
    get: operations["getOrganizationByClaimValue"];
  };
  "/workflows": {
    /**
     * Retrieve All Pending Workflow Processes
     *  
     * @description This operation can be used to retrieve list of workflow pending processes.
     */
    get: {
      parameters: {
        query: {
          limit?: components["parameters"]["limit"];
          offset?: components["parameters"]["offset"];
          /**
           * @description We need to show the values of each workflow process separately.For that we use workflow type.
           * Workflow type can be APPLICATION_CREATION, SUBSCRIPTION_CREATION etc.
           */
          workflowType?: "APPLICATION_CREATION" | "KEY_GENERATION" | "SUBSCRIPTION_CREATION" | "LIFECYCLE_CHANGE";
        };
        header: {
          Accept?: components["parameters"]["Accept"];
        };
      };
      responses: {
        /** @description OK. Workflow pendding process list returned. */
        200: {
          headers: {
            /** @description The content type of the body. */
            "Content-Type"?: string;
          };
          content: {
            "application/json": components["schemas"]["WorkflowList"];
          };
        };
        400: components["responses"]["BadRequest"];
        404: components["responses"]["NotFound"];
        406: components["responses"]["NotAcceptable"];
      };
    };
  };
  "/workflows/update-workflow-status": {
    /**
     * Update Workflow Status 
     * @description This operation can be used to approve or reject a workflow task.
     */
    post: {
      parameters: {
        query: {
          workflowReferenceId: components["parameters"]["workflowReferenceId-Q"];
        };
      };
      /** @description Workflow event that need to be updated */
      requestBody: {
        content: {
          "application/json": components["schemas"]["WorkflowInfo"];
        };
      };
      responses: {
        /** @description OK. Workflow request information is returned. */
        200: {
          headers: {
            /** @description The content type of the body. */
            "Content-Type"?: string;
          };
          content: {
            "application/json": components["schemas"]["WorkflowInfo"];
          };
        };
        400: components["responses"]["BadRequest"];
        404: components["responses"]["NotFound"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Error object returned with 4XX HTTP status */
    Error: {
      /**
       * Format: int64 
       * @description Error code
       */
      code: number;
      /** @description Error message. */
      message: string;
      /** @description A detail description about the error message. */
      description?: string;
      /** @description Preferably an url with more details about the error. */
      moreInfo?: string;
      /**
       * @description If there are more than one error list them out.
       * For example, list out validation errors by each field.
       */
      error?: (components["schemas"]["ErrorListItem"])[];
    };
    /** Description of individual errors that may have occurred during a request. */
    ErrorListItem: {
      /** @description Error code */
      code: string;
      /** @description Description about individual errors occurred */
      message: string;
    };
    /** Policy List */
    PolicyDetailsList: {
      /**
       * @description Number of Throttling Policies returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["PolicyDetails"])[];
    };
    /** Generic Policy */
    PolicyDetails: {
      /**
       * @description Id of policy 
       * @example 3
       */
      policyId?: number;
      /**
       * @description UUId of policy 
       * @example 0c6439fd-9b16-3c2e-be6e-1086e0b9aa93
       */
      uuid?: string;
      /**
       * @description Name of policy 
       * @example 30PerMin
       */
      policyName: string;
      /**
       * @description Display name of the policy 
       * @example 30PerMin
       */
      displayName?: string;
      /**
       * @description Description of the policy 
       * @example Allows 30 request per minute
       */
      description?: string;
      /**
       * @description Indicates whether the policy is deployed successfully or not. 
       * @default false
       */
      isDeployed?: boolean;
      /** @description Indicates the type of throttle policy */
      type?: string;
    };
    /** Generic Throttling Policy */
    Policy: {
      /**
       * @description Id of plan 
       * @example 0c6439fd-9b16-3c2e-be6e-1086e0b9aa93
       */
      planId?: string;
      /**
       * @description Name of plan 
       * @example 30PerMin
       */
      planName: string;
      /**
       * @description Display name of the policy 
       * @example 30PerMin
       */
      displayName?: string;
      /**
       * @description Description of the policy 
       * @example Allows 30 request per minute
       */
      description?: string;
      /**
       * @description Indicates whether the policy is deployed successfully or not. 
       * @default false
       */
      isDeployed?: boolean;
      /** @description Indicates the type of throttle policy */
      type?: string;
    };
    /** Export Policy */
    ExportPolicy: {
      type?: string;
      subtype?: string;
      version?: string;
      data?: Record<string, never>;
    };
    /** Application Throttling Policy */
    ApplicationRatePlan: {
      type: "ApplicationRatePlan";
    } & Omit<components["schemas"]["Policy"], "type"> & {
      defaultLimit: components["schemas"]["ThrottleLimit"];
    };
    /** Application level Rate Plan List */
    ApplicationRatePlanList: {
      /**
       * @description Number of Application Rate Plans returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["ApplicationRatePlan"])[];
    };
    /** Business Plan */
    BusinessPlan: {
      type: "BusinessPlan";
    } & Omit<components["schemas"]["Policy"], "type"> & components["schemas"]["GraphQLQuery"] & {
      defaultLimit: components["schemas"]["ThrottleLimit"];
      /**
       * @description Burst control request count 
       * @example 10
       */
      rateLimitCount?: number;
      /**
       * @description Burst control time unit 
       * @example min
       */
      rateLimitTimeUnit?: string;
      /**
       * @description Number of subscriptions allowed 
       * @example 10
       */
      subscriberCount?: number;
      /**
       * @description Custom attributes added to the Subscription Throttling Policy
       *  
       * @example []
       */
      customAttributes?: (components["schemas"]["CustomAttribute"])[];
      permissions?: components["schemas"]["BusinessPlanPermission"];
    };
    /** Business Plan Permission */
    BusinessPlanPermission: {
      /**
       * @example deny 
       * @enum {string}
       */
      permissionType: "ALLOW" | "DENY";
      /**
       * @example [
       *   "Internal/everyone"
       * ]
       */
      roles: (string)[];
    };
    /** GraphQL Query */
    GraphQLQuery: {
      /**
       * @description Maximum Complexity of the GraphQL query 
       * @example 400
       */
      graphQLMaxComplexity?: number;
      /**
       * @description Maximum Depth of the GraphQL query 
       * @example 10
       */
      graphQLMaxDepth?: number;
    };
    /** Business Plan List */
    BusinessPlanList: {
      /**
       * @description Number of Business Plans returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["BusinessPlan"])[];
    };
    /** Throttle Limit Base */
    ThrottleLimitBase: {
      /**
       * @description Unit of the time. Allowed values are "sec", "min", "hour", "day" 
       * @example min
       */
      timeUnit: string;
      /**
       * @description Time limit that the throttling limit applies. 
       * @example 10
       */
      unitTime: number;
    };
    /** Throttle Limit */
    ThrottleLimit: {
      /**
       * @description Type of the throttling limit. Allowed values are "REQUESTCOUNTLIMIT" and "BANDWIDTHLIMIT".
       * Please see schemas of "RequestCountLimit" and "BandwidthLimit" throttling limit types in
       * Definitions section.
       *  
       * @example REQUESTCOUNTLIMIT 
       * @enum {string}
       */
      type: "REQUESTCOUNTLIMIT" | "BANDWIDTHLIMIT" | "EVENTCOUNTLIMIT";
      requestCount?: components["schemas"]["RequestCountLimit"];
      bandwidth?: components["schemas"]["BandwidthLimit"];
      eventCount?: components["schemas"]["EventCountLimit"];
    };
    /** Bandwidth Limit object */
    BandwidthLimit: components["schemas"]["ThrottleLimitBase"] & {
      /**
       * Format: int64 
       * @description Amount of data allowed to be transferred 
       * @example 1000
       */
      dataAmount: number;
      /**
       * @description Unit of data allowed to be transferred. Allowed values are "KB", "MB" and "GB" 
       * @example KB
       */
      dataUnit: string;
    };
    /** Request Count Limit object */
    RequestCountLimit: components["schemas"]["ThrottleLimitBase"] & {
      /**
       * Format: int64 
       * @description Maximum number of requests allowed 
       * @example 30
       */
      requestCount: number;
    };
    /** Event Count Limit object */
    EventCountLimit: components["schemas"]["ThrottleLimitBase"] & {
      /**
       * Format: int64 
       * @description Maximum number of events allowed 
       * @example 3000
       */
      eventCount: number;
    };
    /**
     * Blocking Conditions 
     * @description Blocking Conditions
     */
    BlockingCondition: {
      /**
       * @description Id of the blocking condition 
       * @example b513eb68-69e8-4c32-92cf-852c101363cf
       */
      policyId?: string;
      /**
       * @description Type of the blocking condition 
       * @example IP 
       * @enum {string}
       */
      conditionType: "API" | "APPLICATION" | "IP" | "IPRANGE" | "USER";
      /**
       * @description Value of the blocking condition 
       * @example {
       *   "fixedIp": "192.168.1.1",
       *   "invert": false
       * }
       */
      conditionValue: Record<string, never>;
      /**
       * @description Status of the blocking condition 
       * @example true
       */
      conditionStatus?: boolean;
    };
    /** Blocking Conditions List */
    BlockingConditionList: {
      /**
       * @description Number of Blocking Conditions returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["BlockingCondition"])[];
    };
    /**
     * Blocking Conditions Status 
     * @description Blocking Conditions Status
     */
    BlockingConditionStatus: {
      /**
       * @description Id of the blocking condition 
       * @example b513eb68-69e8-4c32-92cf-852c101363cf
       */
      policyId?: string;
      /**
       * @description Status of the blocking condition 
       * @example true
       */
      conditionStatus: boolean;
    };
    /** Name-Value pair */
    CustomAttribute: {
      /**
       * @description Name of the custom attribute 
       * @example customAttr1
       */
      name: string;
      /**
       * @description Value of the custom attribute 
       * @example value1
       */
      value: string;
    };
    /** Application List */
    ApplicationList: {
      /**
       * @description Number of applications returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["ApplicationInfo"])[];
      pagination?: components["schemas"]["Pagination"];
    };
    /** Application info object with basic application details */
    ApplicationInfo: {
      /** @example 01234567-0123-0123-0123-012345678901 */
      applicationId?: string;
      /** @example CalculatorApp */
      name?: string;
      /** @example admin */
      owner?: string;
      /** @example APPROVED */
      status?: string;
      /** @example */
      groupId?: string;
    };
    /** Application object with all the application details */
    Application: {
      /** @example 01234567-0123-0123-0123-012345678901 */
      applicationId?: string;
      /** @example CalculatorApp */
      name?: string;
      /** @example Unlimited */
      throttlingPolicy?: string;
      /** @example Sample calculator application */
      description?: string;
      /**
       * @description Type of the access token generated for this application.
       * **OAUTH:** A UUID based access token which is issued by default.
       * **JWT:** A self-contained, signed JWT based access token. **Note:** This can be only used in Microgateway environments.
       *  
       * @default JWT 
       * @example JWT 
       * @enum {string}
       */
      tokenType?: "OAUTH" | "JWT";
      /**
       * @default  
       * @example APPROVED
       */
      status?: string;
      /** @example */
      groups?: (string)[];
      subscriptionCount?: number;
      /** @example External Reference ID, Billing Tier */
      attributes?: {
        [key: string]: string | undefined;
      };
      subscriptionScopes?: (components["schemas"]["ScopeInfo"])[];
      /**
       * @description Application created user
       *  
       * @example admin
       */
      owner?: string;
    };
    /** API Scope info object with scope details */
    ScopeInfo: {
      /** @example admin_scope */
      key?: string;
      /** @example admin scope */
      name?: string;
      /**
       * @description Allowed roles for the scope 
       * @example [
       *   "manager",
       *   "developer"
       * ]
       */
      roles?: (string)[];
      /** @description Description of the scope */
      description?: string;
    };
    /** Environment */
    Environment: {
      /** @example ece92bdc-e1e6-325c-b6f4-656208a041e9 */
      id?: string;
      /** @example us-region */
      name: string;
      /** @example US Region */
      displayName?: string;
      /** @example wso2 */
      provider?: string;
      /** @example Gateway environment in US Region */
      description?: string;
      /** @example false */
      isReadOnly?: boolean;
      vhosts: (components["schemas"]["VHost"])[];
      endpointURIs?: (components["schemas"]["GatewayEnvironmentProtocolURI"])[];
      additionalProperties?: (components["schemas"]["AdditionalProperty"])[];
    };
    /** Environment List */
    EnvironmentList: {
      /**
       * @description Number of Environments returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["Environment"])[];
    };
    /** Virtual Host */
    VHost: {
      /** @example mg.wso2.com */
      host: string;
      /** @example pets */
      httpContext?: string;
      /** @example 80 */
      httpPort?: number;
      /** @example 443 */
      httpsPort?: number;
      /** @example 9099 */
      wsPort?: number;
      /** @example 8099 */
      wssPort?: number;
    };
    /** Additional Gateway Properties */
    AdditionalProperty: {
      /** @example Organization */
      key?: string;
      /** @example wso2 */
      value?: string;
    };
    /** Gateway Environment protocols and URIs */
    GatewayEnvironmentProtocolURI: {
      /** @example default */
      protocol: string;
      /** @example default */
      endpointURI: string;
    };
    /** Usage publish status */
    PublishStatus: {
      /**
       * @description Status of the usage publish request 
       * @example successful
       */
      status?: string;
      /**
       * @description detailed message of the status 
       * @example Records published successfully
       */
      message?: string;
    };
    /** Usage publish status */
    MonetizationUsagePublishInfo: {
      /**
       * @description State of usage publish job 
       * @example RUNNING
       */
      state?: string;
      /**
       * @description Status of usage publish job 
       * @example SUCCESSFULL
       */
      status?: string;
      /**
       * @description Timestamp of the started time of the Job 
       * @example 1599196134000
       */
      startedTime?: string;
      /**
       * @description Timestamp of the last published time 
       * @example 1599196134000
       */
      lastPublsihedTime?: string;
    };
    /**
     * Tenant information 
     * @description The tenant information of the user
     */
    TenantInfo: {
      /** @example john */
      username?: string;
      /** @example carbon.super */
      tenantDomain?: string;
      /** @example -1234 */
      tenantId?: number;
    };
    /**
     * Custom url information 
     * @description The custom url information of the tenant domain
     */
    CustomUrlInfo: {
      /** @example carbon.super */
      tenantDomain?: string;
      /** @example john@foo.com */
      tenantAdminUsername?: string;
      /** @example true */
      enabled?: boolean;
      devPortal?: {
        /** @example http://example.com */
        url?: string;
      };
    };
    /** Organization */
    Organization: {
      /** @example 01234567-0123-0123-0123-012345678901 */
      id?: string;
      /** @example Finance */
      name: string;
      /** @example Finance */
      displayName: string;
      /** @example 01234567-0123-0123-0123 */
      organizationClaimValue?: string;
      /** @default true */
      enabled?: boolean;
      /**
       * @default [
       *   "*"
       * ]
       */
      serviceNamespaces?: (string)[];
      workflows?: (components["schemas"]["WorkflowProperties"])[];
      production?: (string)[];
      sandbox?: (string)[];
    };
    /** Organization List */
    OrganizationList: {
      /**
       * @description Number of Organization returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["Organization"])[];
    };
    /** WorkflowList */
    WorkflowList: {
      /**
       * @description Number of workflow processes returned.
       *  
       * @example 1
       */
      count?: number;
      /**
       * @description Link to the next subset of resources qualified.
       * Empty if no more resources are to be returned.
       *  
       * @example /workflows?limit=1&offset=2&user=
       */
      next?: string;
      /**
       * @description Link to the previous subset of resources qualified.
       * Empty if current subset is the first subset returned.
       *  
       * @example /workflows?limit=1&offset=0&user=
       */
      previous?: string;
      list?: (components["schemas"]["WorkflowInfo"])[];
    };
    /** workflow properties */
    WorkflowProperties: {
      /** @enum {string} */
      name?: "APPLICATION_CREATION" | "KEY_GENERATION" | "SUBSCRIPTION_CREATION" | "LIFECYCLE_CHANGE";
      enable?: boolean;
      properties?: (string)[];
    };
    /** Workflow info object with basic workflow details */
    WorkflowInfo: {
      /**
       * @description Type of the Workflow Request. It shows which type of request is it.
       *  
       * @example APPLICATION_CREATION 
       * @enum {string}
       */
      workflowType?: "APPLICATION_CREATION" | "KEY_GENERATION" | "SUBSCRIPTION_CREATION" | "LIFECYCLE_CHANGE";
      /**
       * @description Show the Status of the the workflow request whether it is approved or created.
       *  
       * @example APPROVED 
       * @enum {string}
       */
      workflowStatus?: "APPROVED" | "CREATED";
      /**
       * @description Time of the the workflow request created.
       *  
       * @example "2020-02-10T10:10:19.704Z"
       */
      createdTime?: string;
      /**
       * @description Time of the the workflow request updated.
       *  
       * @example "2020-02-10T10:10:19.704Z"
       */
      updatedTime?: string;
      /**
       * @description description is a message with basic details about the workflow request.
       *  
       * @example Approve application [APP1] creation request from application creator - admin with throttling tier - 10MinPer
       */
      description?: string;
    };
    /** workflow Response */
    WorkflowResponse: {
      /**
       * @description This attribute declares whether this workflow task is approved or rejected.
       *  
       * @example APPROVED 
       * @enum {string}
       */
      workflowStatus: "CREATED" | "APPROVED" | "REJECTED" | "REGISTERED";
      /** @description Attributes that returned after the workflow execution */
      jsonPayload?: string;
    };
    /** API Category */
    APICategory: {
      /** @example 01234567-0123-0123-0123-012345678901 */
      id?: string;
      /** @example Finance */
      name: string;
      /** @example Finance related APIs */
      description?: string;
      /** @example 1 */
      numberOfAPIs?: number;
    };
    /** API Category List */
    APICategoryList: {
      /**
       * @description Number of API categories returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["APICategory"])[];
    };
    /** Settings */
    Settings: {
      scopes?: (string)[];
      keyManagerConfiguration?: ({
          /** @example default */
          type?: string;
          /** @example default */
          displayName?: string;
          /** @example azp */
          defaultConsumerKeyClaim?: string;
          /** @example scope */
          defaultScopesClaim?: string;
          configurations?: (components["schemas"]["KeyManagerConfiguration"])[];
          endpointConfigurations?: (components["schemas"]["KeyManagerConfiguration"])[];
        })[];
      /**
       * @description To determine whether analytics is enabled or not 
       * @example false
       */
      analyticsEnabled?: boolean;
    };
    /** Key Manager Well-Known Response. */
    KeyManagerWellKnownResponse: {
      /**
       * @default false 
       * @example true
       */
      valid?: boolean;
      value?: components["schemas"]["KeyManager"];
    };
    /** Key Manager */
    KeyManager: {
      /** @example 01234567-0123-0123-0123-012345678901 */
      id?: string;
      /** @example WSO2 Identity Server */
      name: string;
      /**
       * @description display name of Key Manager to  show in UI
       *  
       * @example WSO2 Identity Server
       */
      displayName?: string;
      /** @example WSO2-IS */
      type: string;
      /** @example This is a key manager for Developers */
      description?: string;
      /**
       * @description Well-Known Endpoint of Identity Provider.
       *  
       * @example
       */
      wellKnownEndpoint?: string;
      endpoints?: (components["schemas"]["KeyManagerEndpoint"])[];
      signingCertificate?: {
        /** @enum {string} */
        type?: "JWKS" | "PEM";
        value?: string;
      };
      /** @description PEM type certificate */
      tlsCertificate?: string;
      /** @example https://localhost:9444/services */
      issuer: string;
      availableGrantTypes?: (string)[];
      /**
       * @default true 
       * @example true
       */
      enableTokenGeneration?: boolean;
      /**
       * @default false 
       * @example false
       */
      enableMapOAuthConsumerApps?: boolean;
      /**
       * @default true 
       * @example false
       */
      enableOauthAppValidation?: boolean;
      /**
       * @default true 
       * @example false
       */
      enableOAuthAppCreation?: boolean;
      /** @example azp */
      consumerKeyClaim?: string;
      /** @example scopes */
      scopesClaim?: string;
      /**
       * @default true 
       * @example true
       */
      enabled?: boolean;
      /**
       * @example {
       *   "self_validate_jwt": true,
       *   "Username": "admin",
       *   "Password": "admin"
       * }
       */
      additionalProperties?: Record<string, never>;
    };
    /** Key Manager Endpoint. */
    KeyManagerEndpoint: {
      /** @example token_endpoint */
      name: string;
      /** @example https://localhost:9443/oauth2/token */
      value: string;
    };
    /** Key Manager Info */
    KeyManagerInfo: {
      /** @example 01234567-0123-0123-0123-012345678901 */
      id?: string;
      /** @example WSO2 IS */
      name: string;
      /** @example IS */
      type: string;
      /** @example This is a key manager for Developers */
      description?: string;
      /** @example true */
      enabled?: boolean;
    };
    /** Key Manager Configuration */
    KeyManagerConfiguration: {
      /** @example consumer_key */
      name?: string;
      /** @example Consumer Key */
      label?: string;
      /** @example select */
      type?: string;
      /** @example true */
      required?: boolean;
      /** @example true */
      mask?: boolean;
      /** @example true */
      multiple?: boolean;
      /** @example Enter username to connect to key manager */
      tooltip?: string;
      /** @example admin */
      default?: string;
      values?: (string)[];
    };
    /** Key Manager List */
    KeyManagerList: {
      /**
       * @description Number of Key managers returned.
       *  
       * @example 1
       */
      count?: number;
      list?: (components["schemas"]["KeyManagerInfo"])[];
    };
    /** Claim Mapping Configuration */
    ClaimMappingEntry: {
      /** @example http://idp.org/username */
      remoteClaim?: string;
      /** @example http://wso2.org/username */
      localClaim?: string;
    };
    /** Token handling Configuration */
    TokenValidation: {
      id?: number;
      /**
       * @default true 
       * @example false
       */
      enable?: boolean;
      /** @enum {string} */
      type?: "REFERENCE" | "JWT" | "CUSTOM";
      value?: Record<string, never>;
    };
    /** Pagination */
    Pagination: {
      /** @example 0 */
      offset?: number;
      /** @example 1 */
      limit?: number;
      /** @example 10 */
      total?: number;
      /**
       * @description Link to the next subset of resources qualified.
       * Empty if no more resources are to be returned.
       * example: ""
       */
      next?: string;
      /**
       * @description Link to the previous subset of resources qualified.
       * Empty if current subset is the first subset returned.
       * example: ""
       */
      previous?: string;
    };
  };
  responses: {
    /** @description Bad Request. Invalid request or validation error. */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Conflict. Specified resource already exists. */
    Conflict: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Forbidden. The request must be conditional but no condition has been specified. */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Internal Server Error. */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not Acceptable. The requested media type is not supported. */
    NotAcceptable: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not Found. The specified resource does not exist. */
    NotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Payload Too Large. Request entity is larger than limits defined by server. */
    PayloadTooLarge: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Precondition Failed. The request has not been performed because one of the preconditions is not met. */
    PreconditionFailed: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unauthorized. The user is not authorized. */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unsupported Media Type. The entity of the request was not in a supported format. */
    UnsupportedMediaType: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /**
     * @description Validator for conditional requests; based on the ETag of the formerly retrieved
     * variant of the resource.
     */
    "If-None-Match"?: string;
    /**
     * @description For cross-tenant invocations, this is used to specify the tenant domain, where the resource need to be
     *   retirieved from.
     */
    requestedTenant?: string;
    /** @description Criteria for sorting. */
    sortBy?: "apiName" | "version" | "createdTime" | "status";
    /** @description Order of sorting(ascending/descending). */
    sortOrder?: "asc" | "desc";
    /** @description username of the new application owner */
    username: string;
    /** @description Base64 URL encoded value of the scope name to be validated */
    scopeName: string;
    /** @description Environment UUID (or Environment name defined in config) */
    environmentId: string;
    /** @description Policy UUID */
    policyId: string;
    /** @description Policy UUID */
    planId: string;
    /** @description Custom rule UUID */
    ruleId: string;
    /** @description Application UUID */
    applicationId: string;
    /** @description Media types acceptable for the response. Default is application/json. */
    Accept?: string;
    /** @description Media type of the entity in the body. Default is application/json. */
    "Content-Type": string;
    /** @description Maximum size of resource array to return. */
    limit?: number;
    /** @description Starting point within the complete list of items qualified. */
    offset?: number;
    /** @description username of the application creator */
    user?: string;
    /** @description Workflow reference id */
    "workflowReferenceId-Q": string;
    /** @description API Category UUID */
    apiCategoryId: string;
    /** @description Organization UUID */
    organizationId: string;
    /** @description Key Manager UUID */
    keyManagerId: string;
    /**
     * @description The Base 64 URL encoded role name with domain. If the given role is in PRIMARY user-store, role ID should be
     * derived as Base64URLEncode(role-name). If the given role is in secondary user-store, role ID should be
     * derived as Base64URLEncode({user-store-name}/{role-name}).
     */
    roleId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * Retrieve/Search Policies
   *  
   * @description This operation provides you a list of available Policies qualifying the given keyword match.
   */
  policySearch: {
    parameters: {
      query: {
        /**
         * @description **Search**.
         * You can search by providing a keyword. Allowed to search by type and name only.
         */
        query?: string;
      };
    };
    responses: {
      /** @description OK.List of qualifying Policies is returned. */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["PolicyDetailsList"];
        };
      };
    };
  };
  /**
   * Get all Application Rate Plans 
   * @description Retrieves all existing application rate plans.
   */
  getApplicationRatePlans: {
    parameters: {
      header: {
        Accept?: components["parameters"]["Accept"];
      };
    };
    responses: {
      /** @description OK. Policies returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRatePlanList"];
        };
      };
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Add an Application Rate Plan 
   * @description This operation can be used to add a new application level rate plan.
   */
  addApplicationRatePlan: {
    parameters: {
      header: {
        "Content-Type": components["parameters"]["Content-Type"];
      };
    };
    /** @description Application level policy object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationRatePlan"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created object as entity in the body. Location header contains URL of newly created entity. */
      201: {
        headers: {
          /** @description Location of the newly created Policy object. */
          Location?: string;
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRatePlan"];
        };
      };
      400: components["responses"]["BadRequest"];
      415: components["responses"]["UnsupportedMediaType"];
    };
  };
  /**
   * Get an Application Rate Plan 
   * @description Retrieves an application rate plan.
   */
  getApplicationRatePlanById: {
    parameters: {
      path: {
        planId: components["parameters"]["planId"];
      };
    };
    responses: {
      /** @description OK. Plan returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRatePlan"];
        };
      };
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Update an Application Rate Plan 
   * @description Updates an existing application level rate plan. Upon a successful update, you will receive the updated application plan as the response.
   */
  updateApplicationRatePlan: {
    parameters: {
      header: {
        "Content-Type": components["parameters"]["Content-Type"];
      };
      path: {
        planId: components["parameters"]["planId"];
      };
    };
    /** @description Policy object that needs to be modified */
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplicationRatePlan"];
      };
    };
    responses: {
      /** @description OK. Plan updated. */
      200: {
        headers: {
          /** @description The URL of the newly created resource. */
          Location?: string;
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["ApplicationRatePlan"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete an Application Rate Plan 
   * @description Deletes an application level rate plan.
   */
  removeApplicationRatePlan: {
    parameters: {
      path: {
        planId: components["parameters"]["planId"];
      };
    };
    responses: {
      /** @description OK. Resource successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Get all Business Plans 
   * @description This operation can be used to retrieve all Business Plans.
   */
  getAllBusinessPlans: {
    parameters: {
      header: {
        Accept?: components["parameters"]["Accept"];
      };
    };
    responses: {
      /** @description OK. Plans returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BusinessPlanList"];
        };
      };
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Add a Business Plan 
   * @description This operation can be used to add a  Business Plan specifying the details of the plan in the payload.
   */
  addBusinessPlan: {
    parameters: {
      header: {
        "Content-Type": components["parameters"]["Content-Type"];
      };
    };
    /** @description Business Plan object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessPlan"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created object as entity in the body. Location header contains URL of newly created entity. */
      201: {
        headers: {
          /** @description Location of the newly created Plan object. */
          Location?: string;
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BusinessPlan"];
        };
      };
      400: components["responses"]["BadRequest"];
      415: components["responses"]["UnsupportedMediaType"];
    };
  };
  /**
   * Get a Business Plan 
   * @description This operation can be used to retrieves Business Plan by specifying the Id of the plan as a path parameter
   */
  getBusinessPlanById: {
    parameters: {
      path: {
        planId: components["parameters"]["planId"];
      };
    };
    responses: {
      /** @description OK. Plan returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BusinessPlan"];
        };
      };
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Update a Business Plan 
   * @description Updates an existing Business Plan.
   */
  updateBusinessPlan: {
    parameters: {
      header: {
        "Content-Type": components["parameters"]["Content-Type"];
      };
      path: {
        planId: components["parameters"]["planId"];
      };
    };
    /** @description Plan object that needs to be modified */
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessPlan"];
      };
    };
    responses: {
      /** @description OK. Plan updated. */
      200: {
        headers: {
          /** @description The URL of the newly created resource. */
          Location?: string;
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BusinessPlan"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete a Business Plan 
   * @description This operation can be used to delete a business plan by specifying the Id of the plan as a path parameter.
   */
  removeBusinessPlan: {
    parameters: {
      path: {
        planId: components["parameters"]["planId"];
      };
    };
    responses: {
      /** @description OK. Resource successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Export a Throttling Policy 
   * @description This operation can be used to export the details of a particular Throttling Policy.
   */
  exportThrottlingPolicy: {
    parameters: {
      query: {
        /** @description UUID of the ThrottlingPolicy */
        policyId?: string;
        /** @description Throttling Policy Name */
        name?: string;
        /** @description Type of the Throttling Policy */
        type?: "sub" | "app" | "api" | "global";
        /** @description Format of output documents. Can be YAML or JSON. */
        format?: "JSON" | "YAML";
      };
    };
    responses: {
      /** @description OK. Export Successful. */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["ExportPolicy"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Import a Throttling Policy 
   * @description This operation can be used to import a Throttling Policy.
   */
  importThrottlingPolicy: {
    parameters: {
      query: {
        /** @description Update an existing throttling policy with the same name. */
        overwrite?: boolean;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary 
           * @description Json File
           */
          file: string;
        };
      };
    };
    responses: {
      /** @description Created. Throttling Policy Imported Successfully. */
      200: never;
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /**
   * Get all Deny Policies 
   * @description Retrieves all existing deny policies.
   */
  getAllDenyPolicies: {
    parameters: {
      header: {
        Accept?: components["parameters"]["Accept"];
      };
    };
    responses: {
      /** @description OK. Deny Policies returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BlockingConditionList"];
        };
      };
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Add a deny policy 
   * @description Adds a new deny policy
   */
  addDenyPolicy: {
    parameters: {
      header: {
        "Content-Type": components["parameters"]["Content-Type"];
      };
    };
    /** @description Blocking condition object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlockingCondition"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created object as entity in the body. Location header contains URL of newly created entity. */
      201: {
        headers: {
          /** @description Location of the newly created resource. */
          Location?: string;
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BlockingCondition"];
        };
      };
      400: components["responses"]["BadRequest"];
      415: components["responses"]["UnsupportedMediaType"];
    };
  };
  /**
   * Get a Deny Policy 
   * @description Retrieves a Deny policy providing the policy Id
   */
  getDenyPolicyById: {
    parameters: {
      path: {
        policyId: components["parameters"]["policyId"];
      };
    };
    responses: {
      /** @description OK. Condition returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["BlockingCondition"];
        };
      };
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Delete a Deny Policy 
   * @description Deletes an existing deny policy
   */
  removeDenyPolicy: {
    parameters: {
      path: {
        policyId: components["parameters"]["policyId"];
      };
    };
    responses: {
      /** @description OK. Resource successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Update a Deny Policy 
   * @description Update a deny policy by Id
   */
  updateDenyPolicy: {
    parameters: {
      header: {
        "Content-Type": components["parameters"]["Content-Type"];
      };
      path: {
        policyId: components["parameters"]["policyId"];
      };
    };
    /** @description Blocking condition with updated status */
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlockingConditionStatus"];
      };
    };
    responses: {
      /** @description OK. Resource successfully updated. */
      200: {
        content: {
          "application/json": components["schemas"]["BlockingCondition"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Retrieve/Search Applications
   *  
   * @description This operation can be used to retrieve list of applications owned by the given user, If no user
   * is provided, the applications owned by the user associated with the provided access token will be returned.
   */
  getApplicationsByUser: {
    parameters: {
      query: {
        user?: components["parameters"]["user"];
        limit?: components["parameters"]["limit"];
        offset?: components["parameters"]["offset"];
        /** @description Application Name */
        name?: string;
        /**
         * @description Tenant domain of the applications to get. This has to be specified only if it is required to get applications of
         * a tenant other than the requester's tenant. So, if not specified, the default will be set as the
         * requester's tenant domain. This cross tenant Application access is allowed only for super tenant admin
         * users **only at a migration process**.
         */
        tenantDomain?: string;
        sortBy?: "name" | "owner";
        sortOrder?: "asc" | "desc";
      };
      header: {
        Accept?: components["parameters"]["Accept"];
      };
    };
    responses: {
      /** @description OK. Application list returned. */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["ApplicationList"];
        };
      };
      400: components["responses"]["BadRequest"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Get the details of an Application
   *  
   * @description This operation can be used to get the details of an application by specifying its id.
   */
  getApplicationById: {
    parameters: {
      path: {
        applicationId: components["parameters"]["applicationId"];
      };
    };
    responses: {
      /** @description OK. Application details returned. */
      200: {
        content: {
          "application/json": components["schemas"]["Application"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Delete an Application
   *  
   * @description This operation can be used to delete an application by specifying its id.
   */
  removeApplication: {
    parameters: {
      path: {
        applicationId: components["parameters"]["applicationId"];
      };
    };
    responses: {
      /** @description OK. Resource successfully deleted. */
      200: {
        content: {
        };
      };
      /** @description Accepted. The request has been accepted. */
      202: {
        headers: {
          /** @description Location of the existing Application. */
          Location?: string;
        };
        content: {
          "application/json": components["schemas"]["WorkflowResponse"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Change Application Owner 
   * @description This operation is used to change the owner of an Application.
   * In order to change the owner of an application, we need to pass the new application owner as a query parameter
   */
  changeApplicationOwner: {
    parameters: {
      query: {
        owner: string;
      };
      path: {
        applicationId: components["parameters"]["applicationId"];
      };
    };
    responses: {
      /** @description OK. Application owner changed successfully. */
      200: {
        content: {
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Get all registered Environments 
   * @description Get all Registered Environments
   */
  getEnvironments: {
    responses: {
      /** @description OK. Environments returned */
      200: {
        content: {
          "application/json": components["schemas"]["EnvironmentList"];
        };
      };
    };
  };
  /**
   * Add an Environment 
   * @description Add a new gateway environment
   */
  addEnvironment: {
    /** @description Environment object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Environment"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created environment as entity in the body. */
      201: {
        content: {
          "application/json": components["schemas"]["Environment"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Update an Environment 
   * @description Update a gateway Environment by environment Id
   */
  updateEnvironment: {
    parameters: {
      path: {
        environmentId: components["parameters"]["environmentId"];
      };
    };
    /** @description Environment object with updated information */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Environment"];
      };
    };
    responses: {
      /** @description OK. Environment updated. */
      200: {
        content: {
          "application/json": components["schemas"]["Environment"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete an Environment 
   * @description Delete a Environment by Environment Id
   */
  removeEnvironment: {
    parameters: {
      path: {
        environmentId: components["parameters"]["environmentId"];
      };
    };
    responses: {
      /** @description OK. Environment successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Get Tenant Id of User
   *  
   * @description This operation is to get tenant id of the provided user
   */
  getTenantInfoByUsername: {
    parameters: {
      path: {
        /** @description The state represents the current state of the tenant. Supported states are [ active, inactive] */
        username: string;
      };
    };
    responses: {
      /** @description OK. Tenant id of the user retrieved. */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["TenantInfo"];
        };
      };
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Get Custom URL Info of a Tenant Domain
   *  
   * @description This operation is to get custom-url information of the provided tenant-domain
   */
  getCustomUrlInfoByTenantDomain: {
    parameters: {
      path: {
        /** @description The tenant domain name. */
        tenantDomain: string;
      };
    };
    responses: {
      /** @description OK. Custom url info of the tenant is retrieved. */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["CustomUrlInfo"];
        };
      };
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Get all API Categories 
   * @description Get all API categories
   */
  getAllCategories: {
    responses: {
      /** @description OK. Categories returned */
      200: {
        content: {
          "application/json": components["schemas"]["APICategoryList"];
        };
      };
    };
  };
  /**
   * Add API Category 
   * @description Add a new API category
   */
  addCategory: {
    /** @description API Category object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["APICategory"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created object as entity in the body. */
      201: {
        content: {
          "application/json": components["schemas"]["APICategory"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Update an API Category 
   * @description Update an API Category by category Id
   */
  updateCategory: {
    parameters: {
      path: {
        apiCategoryId: components["parameters"]["apiCategoryId"];
      };
    };
    /** @description API Category object with updated information */
    requestBody: {
      content: {
        "application/json": components["schemas"]["APICategory"];
      };
    };
    responses: {
      /** @description OK. Label updated. */
      200: {
        content: {
          "application/json": components["schemas"]["APICategory"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete an API Category 
   * @description Delete an API Category by API Category Id
   */
  removeCategory: {
    parameters: {
      path: {
        apiCategoryId: components["parameters"]["apiCategoryId"];
      };
    };
    responses: {
      /** @description OK. API Category successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Retrieve Admin Settings 
   * @description Retrieve admin settings
   */
  getAdminSettings: {
    responses: {
      /** @description OK. Settings returned */
      200: {
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Get all Key managers 
   * @description Get all Key managers
   */
  getAllKeyManagers: {
    responses: {
      /** @description OK. KeyManagers returned */
      200: {
        content: {
          "application/json": components["schemas"]["KeyManagerList"];
        };
      };
    };
  };
  /**
   * Add a new API Key Manager 
   * @description Add a new API Key Manager
   */
  addNewKeyManager: {
    /** @description Key Manager object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["KeyManager"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created object as entity in the body. */
      201: {
        content: {
          "application/json": components["schemas"]["KeyManager"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Get a Key Manager Configuration 
   * @description Retrieve a single Key Manager Configuration. We should provide the Id of the KeyManager as a path parameter.
   */
  getKeyManagerConfiguration: {
    parameters: {
      path: {
        keyManagerId: components["parameters"]["keyManagerId"];
      };
    };
    responses: {
      /** @description OK. KeyManager Configuration returned */
      200: {
        headers: {
          /** @description The content type of the body. */
          "Content-Type"?: string;
        };
        content: {
          "application/json": components["schemas"]["KeyManager"];
        };
      };
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Update a Key Manager 
   * @description Update a Key Manager by keyManager ID
   */
  updateKeyManager: {
    parameters: {
      path: {
        keyManagerId: components["parameters"]["keyManagerId"];
      };
    };
    /** @description Key Manager object with updated information */
    requestBody: {
      content: {
        "application/json": components["schemas"]["KeyManager"];
      };
    };
    responses: {
      /** @description OK. Label updated. */
      200: {
        content: {
          "application/json": components["schemas"]["KeyManager"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete a Key Manager 
   * @description Delete a Key Manager by keyManager id
   */
  removeKeyManager: {
    parameters: {
      path: {
        keyManagerId: components["parameters"]["keyManagerId"];
      };
    };
    responses: {
      /** @description OK. Key Manager successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Retrieve Well-known information from Key Manager Well-known Endpoint 
   * @description Retrieve well-known information from key manager's well-known endpoint
   */
  getWellKnownInfoKeyManager: {
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** @description Well-Known Endpoint */
          url?: string;
          /**
           * @description Key Manager Type
           *  
           * @default false
           */
          type?: string;
        };
      };
    };
    responses: {
      /** @description OK. KeyManagers returned */
      200: {
        content: {
          "application/json": components["schemas"]["KeyManagerWellKnownResponse"];
        };
      };
    };
  };
  /**
   * Get all Organization 
   * @description Get all Organization
   */
  getAllOrganization: {
    responses: {
      /** @description OK. Organization returned */
      200: {
        content: {
          "application/json": components["schemas"]["OrganizationList"];
        };
      };
    };
  };
  /**
   * Add Organization 
   * @description Add a new Organization
   */
  addOrganization: {
    /** @description Organization object that should to be added */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      /** @description Created. Successful response with the newly created object as entity in the body. */
      201: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Get the details of an Organization
   *  
   * @description This operation can be used to get the details of an Organization by specifying its id.
   */
  getOrganizationById: {
    parameters: {
      path: {
        organizationId: components["parameters"]["organizationId"];
      };
    };
    responses: {
      /** @description OK. Application details returned. */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      406: components["responses"]["NotAcceptable"];
    };
  };
  /**
   * Update an Organization 
   * @description Update an Organization by organization Id
   */
  updateOrganization: {
    parameters: {
      path: {
        organizationId: components["parameters"]["organizationId"];
      };
    };
    /** @description Organization object with updated information */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
    responses: {
      /** @description OK. Label updated. */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete an Organization 
   * @description Delete an Organization by API Organization Id
   */
  removeOrganization: {
    parameters: {
      path: {
        organizationId: components["parameters"]["organizationId"];
      };
    };
    responses: {
      /** @description OK. Organization successfully deleted. */
      200: {
        content: {
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Authenticate Organization info
   *  
   * @description This operation can be used to authenticate Organization by specifying its claimValue.
   */
  getOrganizationByClaimValue: {
    responses: {
      /** @description OK. Application details returned. */
      200: {
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
}
